---
apiVersion: v1
kind: Secret
metadata:
  name: my-app2-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/mostmark-janus-demo2/my-app2-gitops